Import thư viện và đọc dữ liệu

In [34]:
import pandas as pd
import numpy as np

In [35]:
data = pd.read_csv("../data/Telco-Customer-Churn.csv")

In [36]:
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

Một số thao tác check data

In [37]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [38]:
data.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [39]:
sample = 3
data.sample(sample)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
1639,4690-LLKUA,Male,1,No,No,17,Yes,No,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,45.05,770.6,Yes
4755,8849-AYPTR,Male,0,Yes,No,33,Yes,No,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,No,Electronic check,91.25,2964.05,No
3329,5366-OBVMR,Female,0,Yes,No,18,Yes,No,DSL,No,...,No,Yes,No,No,Month-to-month,Yes,Mailed check,50.30,908.75,No

Xử lý dữ liệu

In [40]:
df1 = data.copy()

xóa cột customerId

In [41]:
df1.drop("customerID", axis=1, inplace=True)

In [42]:
df1.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

xử lý cột gender

In [43]:
df1["gender"] = df1["gender"].map({
    "Male":1,
    "Female":0
})

xử lý 2 cột partner và dependents

In [44]:
df1["Partner"] = df1["Partner"].map({
    "Yes":1,
    "No":0
})
df1["Dependents"] = df1["Dependents"].map({
    "Yes":1,
    "No":0
})

xử lý phoneService

In [45]:
df1["PhoneService"] = df1["PhoneService"].map({
    "Yes":1,
    "No":0
})

In [46]:
df1.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,1,0,0,0,34,1,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,1,0,0,0,2,1,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,1,0,0,0,45,0,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,0,0,0,0,2,1,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

One hot multipleLines

In [47]:
df1['MultipleLines'].unique()

<StringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str

In [48]:
multipleLines_dummies = pd.get_dummies(
    df1["MultipleLines"],
    prefix="MultipleLines",
    drop_first=True
)

df1 = pd.concat([df1, multipleLines_dummies], axis=1)

df1 = df1.drop("MultipleLines", axis=1)

one hot InternetService

In [49]:
df1['InternetService'].unique()

<StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str

In [50]:
internet_dummies = pd.get_dummies(
    df1["InternetService"],
    prefix="InternetService",
    drop_first=True
)

df1 = pd.concat([df1, internet_dummies], axis=1)

df1 = df1.drop("InternetService", axis=1)

one hot OnlineSecurity

In [52]:
df1["OnlineSecurity"].unique()

<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

In [53]:
online_security_dummies = pd.get_dummies(
    df1["OnlineSecurity"],
    prefix="OnlineSecurity",
    drop_first=True
)

df1 = pd.concat([df1, online_security_dummies], axis=1)

df1 = df1.drop("OnlineSecurity", axis=1)

one hot OnlineBackup

In [55]:
df1["OnlineBackup"].unique()

<StringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str

In [56]:
online_backup_dummies = pd.get_dummies(
    df1["OnlineBackup"],
    prefix="OnlineBackup",
    drop_first=True
)

df1 = pd.concat([df1, online_backup_dummies], axis=1)

df1 = df1.drop("OnlineBackup", axis=1)

one hot DeviceProtection

In [58]:
df1["DeviceProtection"].unique()

<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

In [59]:
device_protection_dummies = pd.get_dummies(
    df1["DeviceProtection"],
    prefix="DeviceProtection",
    drop_first=True
)

df1 = pd.concat([df1, device_protection_dummies], axis=1)

df1 = df1.drop("DeviceProtection", axis=1)

one hot TechSupport

In [61]:
df1["TechSupport"].unique()

<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

In [62]:
tech_support_dummies = pd.get_dummies(
    df1["TechSupport"],
    prefix="TechSupport",
    drop_first=True
)

df1 = pd.concat([df1, tech_support_dummies], axis=1)

df1 = df1.drop("TechSupport", axis=1)

one hot StreamingTV

In [64]:
df1["StreamingTV"].unique()

<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

In [65]:
streaming_tv_dummies = pd.get_dummies(
    df1["StreamingTV"],
    prefix="StreamingTV",
    drop_first=True
)

df1 = pd.concat([df1, streaming_tv_dummies], axis=1)

df1 = df1.drop("StreamingTV", axis=1)

one hot StreamingMovies

In [67]:
df1["StreamingMovies"].unique()

<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

In [68]:
streaming_movies_dummies = pd.get_dummies(
    df1["StreamingMovies"],
    prefix="StreamingMovies",
    drop_first=True
)

df1 = pd.concat([df1, streaming_movies_dummies], axis=1)

df1 = df1.drop("StreamingMovies", axis=1)

In [69]:
df1.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,...,OnlineBackup_No internet service,OnlineBackup_Yes,DeviceProtection_No internet service,DeviceProtection_Yes,TechSupport_No internet service,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes
0,0,0,1,0,1,0,Month-to-month,Yes,Electronic check,29.85,...,False,True,False,False,False,False,False,False,False,False
1,1,0,0,0,34,1,One year,No,Mailed check,56.95,...,False,False,False,True,False,False,False,False,False,False
2,1,0,0,0,2,1,Month-to-month,Yes,Mailed check,53.85,...,False,True,False,False,False,False,False,False,False,False
3,1,0,0,0,45,0,One year,No,Bank transfer (automatic),42.30,...,False,False,False,True,False,True,False,False,False,False
4,0,0,0,0,2,1,Month-to-month,Yes,Electronic check,70.70,...,False,False,False,False,False,False,False,False,False,False

Ordinal Encoding contract

In [72]:
df1["Contract"].unique()
df1["Contract"].value_counts()
df1["Contract"].isnull().sum()

np.int64(0)

In [73]:
df1["Contract"] = df1["Contract"].map({
    "Month-to-month": 0,
    "One year": 1,
    "Two year": 2
})

Binary Encoding PaperlessBilling

In [75]:
df1["PaperlessBilling"].unique()

<StringArray>
['Yes', 'No']
Length: 2, dtype: str

In [76]:
df1["PaperlessBilling"] = df1["PaperlessBilling"].map({
    "Yes": 1,
    "No": 0
})

one hot PaymentMethod

In [78]:
df1["PaymentMethod"].unique()

<StringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str

In [79]:
payment_method_dummies = pd.get_dummies(
    df1["PaymentMethod"],
    prefix="PaymentMethod",
    drop_first=True
)
df1 = pd.concat([df1, payment_method_dummies], axis=1)
df1 = df1.drop("PaymentMethod", axis=1)

In [80]:
df1.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,Contract,PaperlessBilling,MonthlyCharges,TotalCharges,...,DeviceProtection_Yes,TechSupport_No internet service,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,1,0,1,0,0,1,29.85,29.85,...,False,False,False,False,False,False,False,False,True,False
1,1,0,0,0,34,1,1,0,56.95,1889.5,...,True,False,False,False,False,False,False,False,False,True
2,1,0,0,0,2,1,0,1,53.85,108.15,...,False,False,False,False,False,False,False,False,False,True
3,1,0,0,0,45,0,1,0,42.30,1840.75,...,True,False,True,False,False,False,False,False,False,False
4,0,0,0,0,2,1,0,1,70.70,151.65,...,False,False,False,False,False,False,False,False,True,False

In [81]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 30 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   gender                                 7043 non-null   int64
 1   SeniorCitizen                          7043 non-null   int64
 2   Partner                                7043 non-null   int64
 3   Dependents                             7043 non-null   int64
 4   tenure                                 7043 non-null   int64
 5   PhoneService                           7043 non-null   int64
 6   Contract                               7043 non-null   int64
 7   PaperlessBilling                       7043 non-null   int64
 8   MonthlyCharges                         7043 non-null   float64
 9   TotalCharges                           7043 non-null   str
 10  Churn                                  7043 non-null   str
 11  MultipleLines_No phone service         7043 non-null   bool
 12  MultipleLines_Yes                      7043 non-null   bool
 13  InternetService_Fiber optic            7043 non-null   bool
 14  InternetService_No                     7043 non-null   bool
 15  OnlineSecurity_No internet service     7043 non-null   bool
 16  OnlineSecurity_Yes                     7043 non-null   bool
 17  OnlineBackup_No internet service       7043 non-null   bool
 18  OnlineBackup_Yes                       7043 non-null   bool
 19  DeviceProtection_No internet service   7043 non-null   bool
 20  DeviceProtection_Yes                   7043 non-null   bool
 21  TechSupport_No internet service        7043 non-null   bool
 22  TechSupport_Yes                        7043 non-null   bool
 23  StreamingTV_No internet service        7043 non-null   bool
 24  StreamingTV_Yes                        7043 non-null   bool
 25  StreamingMovies_No internet service    7043 non-null   bool
 26  StreamingMovies_Yes                    7043 non-null   bool
 27  PaymentMethod_Credit card (automatic)  7043 non-null   bool
 28  PaymentMethod_Electronic check         7043 non-null   bool
 29  PaymentMethod_Mailed check             7043 non-null   bool
dtypes: bool(19), float64(1), int64(8), str(2)
memory usage: 736.1 KB

xử lý cột TotalCharges

In [82]:
df1["TotalCharges"].dtype

In [83]:
df1["TotalCharges"].unique()[:10]

<StringArray>
[  '29.85',  '1889.5',  '108.15', '1840.75',  '151.65',   '820.5',  '1949.4',
   '301.9', '3046.05', '3487.95']
Length: 10, dtype: str

In [84]:
df1["TotalCharges"].isnull().sum()

np.int64(0)

In [85]:
df1["TotalCharges"] = pd.to_numeric(
    df1["TotalCharges"],
    errors="coerce"
)

In [86]:
df1["TotalCharges"].isnull().sum()

np.int64(11)

In [87]:
df1 = df1.dropna()

In [89]:
df1 = df1.reset_index(drop=True)
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 30 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   gender                                 7032 non-null   int64
 1   SeniorCitizen                          7032 non-null   int64
 2   Partner                                7032 non-null   int64
 3   Dependents                             7032 non-null   int64
 4   tenure                                 7032 non-null   int64
 5   PhoneService                           7032 non-null   int64
 6   Contract                               7032 non-null   int64
 7   PaperlessBilling                       7032 non-null   int64
 8   MonthlyCharges                         7032 non-null   float64
 9   TotalCharges                           7032 non-null   float64
 10  Churn                                  7032 non-null   str
 11  MultipleLines_No phone service         7032 non-null   bool
 12  MultipleLines_Yes                      7032 non-null   bool
 13  InternetService_Fiber optic            7032 non-null   bool
 14  InternetService_No                     7032 non-null   bool
 15  OnlineSecurity_No internet service     7032 non-null   bool
 16  OnlineSecurity_Yes                     7032 non-null   bool
 17  OnlineBackup_No internet service       7032 non-null   bool
 18  OnlineBackup_Yes                       7032 non-null   bool
 19  DeviceProtection_No internet service   7032 non-null   bool
 20  DeviceProtection_Yes                   7032 non-null   bool
 21  TechSupport_No internet service        7032 non-null   bool
 22  TechSupport_Yes                        7032 non-null   bool
 23  StreamingTV_No internet service        7032 non-null   bool
 24  StreamingTV_Yes                        7032 non-null   bool
 25  StreamingMovies_No internet service    7032 non-null   bool
 26  StreamingMovies_Yes                    7032 non-null   bool
 27  PaymentMethod_Credit card (automatic)  7032 non-null   bool
 28  PaymentMethod_Electronic check         7032 non-null   bool
 29  PaymentMethod_Mailed check             7032 non-null   bool
dtypes: bool(19), float64(2), int64(8), str(1)
memory usage: 734.9 KB

In [90]:
df1["TotalCharges"].dtype

dtype('float64')

In [91]:
df1.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,Contract,PaperlessBilling,MonthlyCharges,TotalCharges,...,DeviceProtection_Yes,TechSupport_No internet service,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,1,0,1,0,0,1,29.85,29.85,...,False,False,False,False,False,False,False,False,True,False
1,1,0,0,0,34,1,1,0,56.95,1889.50,...,True,False,False,False,False,False,False,False,False,True
2,1,0,0,0,2,1,0,1,53.85,108.15,...,False,False,False,False,False,False,False,False,False,True
3,1,0,0,0,45,0,1,0,42.30,1840.75,...,True,False,True,False,False,False,False,False,False,False
4,0,0,0,0,2,1,0,1,70.70,151.65,...,False,False,False,False,False,False,False,False,True,False

Xử lý cột Chur( target)

In [92]:
df1["Churn"].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [93]:
df1["Churn"] = df1["Churn"].map({
    "Yes": 1,
    "No": 0
})

In [94]:
df1["Churn"].head()

0    0
1    0
2    1
3    0
4    1
Name: Churn, dtype: int64

bắt đầu việc tạo dữ liệu để train và test

In [101]:
X = df1.drop('Churn',axis=1)
y = df1['Churn']
X.head()
y.head()

0    0
1    0
2    1
3    0
4    1
Name: Churn, dtype: int64

dùng thư viện để tách

In [102]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [103]:
print(X_train.shape)

print(X_test.shape)

print(y_train.shape)

print(y_test.shape)

(5625, 29)
(1407, 29)
(5625,)
(1407,)

scaling các cột số về các số nhỏ

In [104]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

num_cols = [
    "tenure",
    "MonthlyCharges",
    "TotalCharges"
]

Scale train set

In [105]:
X_train[num_cols] = scaler.fit_transform(
    X_train[num_cols]
)

Scale test set

In [106]:
X_test[num_cols] = scaler.transform(
    X_test[num_cols]
)

Train model

In [107]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression()

In [108]:
y_pred = model.predict(X_test)

In [109]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.7882018479033405

Classification Report

In [110]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.89      0.86      1033
           1       0.62      0.51      0.56       374

    accuracy                           0.79      1407
   macro avg       0.73      0.70      0.71      1407
weighted avg       0.78      0.79      0.78      1407

confusion matrix

In [111]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred))

[[918 115]
 [183 191]]

Save model

In [115]:
import joblib

joblib.dump(model, "../model/model.pkl")

['../model/model.pkl']

Save scaler

In [116]:
joblib.dump(scaler, "../model/scaler.pkl")

['../model/scaler.pkl']